import "dotenv/config";import express from"express";import cors from"cors";import http from"http";import jwt from"jsonwebtoken";import bcrypt from"bcryptjs";import{Server}from"socket.io";import{PrismaClient}from"@prisma/client";
const db=new PrismaClient(),app=express(),srv=http.createServer(app);app.use(cors({origin:process.env.CLIENT_ORIGIN,credentials:true}));app.use(express.json({limit:"32kb"}));const pub=u=>({id:u.id,username:u.username,avatar:u.avatar,coins:u.coins,gems:u.gems,level:u.level,xp:u.xp,bio:u.bio});
const auth=(req,res,next)=>{try{const h=req.headers.authorization||"";req.uid=jwt.verify(h.replace("Bearer ",""),process.env.JWT_SECRET).sub;next()}catch{res.status(401).json({error:"Unauthorized"})}};
app.get("/health",(_,r)=>r.json({ok:true}));app.post("/api/auth/register",async(req,res)=>{try{let u=String(req.body.username||"").trim(),p=String(req.body.password||"");if(!/^[A-Za-z0-9_]{3,20}$/.test(u)||p.length<8)return res.status(400).json({error:"Username 3-20 chars; password 8+."});if(await db.user.findUnique({where:{username:u}}))return res.status(409).json({error:"Username exists"});let x=await db.user.create({data:{username:u,passwordHash:await bcrypt.hash(p,12),avatar:{outfit:0,hair:0}}});res.json({token:jwt.sign({sub:x.id},process.env.JWT_SECRET,{expiresIn:"7d"}),user:pub(x)})}catch{res.status(500).json({error:"Registration failed"})}});
app.post("/api/auth/login",async(req,res)=>{let x=await db.user.findUnique({where:{username:String(req.body.username||"").trim()}});if(!x||!(await bcrypt.compare(String(req.body.password||""),x.passwordHash)))return res.status(401).json({error:"Invalid login"});res.json({token:jwt.sign({sub:x.id},process.env.JWT_SECRET,{expiresIn:"7d"}),user:pub(x)})});
app.get("/api/me",auth,async(req,res)=>res.json(pub(await db.user.findUnique({where:{id:req.uid}}))));app.patch("/api/me",auth,async(req,res)=>{let d={};if(typeof req.body.bio==="string")d.bio=req.body.bio.slice(0,300);if(req.body.avatar)d.avatar=req.body.avatar;res.json(pub(await db.user.update({where:{id:req.uid},data:d})))});
app.get("/api/friends",auth,async(req,res)=>{let a=await db.friendship.findMany({where:{OR:[{fromId:req.uid},{toId:req.uid}]},include:{from:true,to:true}});res.json(a.map(x=>({id:x.id,status:x.status,user:pub(x.fromId===req.uid?x.to:x.from)})))});
const io=new Server(srv,{cors:{origin:process.env.CLIENT_ORIGIN,credentials:true}}),users=new Map(),players=new Map();function send(id,e,d){for(const s of users.get(id)||[])io.to(s).emit(e,d)}
app.post("/api/friends/request",auth,async(req,res)=>{let t=await db.user.findUnique({where:{username:String(req.body.username||"").trim()}});if(!t||t.id===req.uid)return res.status(404).json({error:"Player not found"});let old=await db.friendship.findFirst({where:{OR:[{fromId:req.uid,toId:t.id},{fromId:t.id,toId:req.uid}]}});if(old)return res.status(409).json({error:"Request exists"});let f=await db.friendship.create({data:{fromId:req.uid,toId:t.id}});send(t.id,"friend:request",{id:f.id});res.json({ok:true})});
app.post("/api/friends/:id/accept",auth,async(req,res)=>{let f=await db.friendship.findFirst({where:{id:req.params.id,toId:req.uid,status:"PENDING"}});if(!f)return res.status(404).json({error:"Request not found"});await db.friendship.update({where:{id:f.id},data:{status:"ACCEPTED"}});send(f.fromId,"friend:accepted",{id:f.id});res.json({ok:true})});
app.post("/api/rooms/invite",auth,async(req,res)=>{let to=String(req.body.receiverId||""),room=String(req.body.roomId||"");let f=await db.friendship.findFirst({where:{status:"ACCEPTED",OR:[{fromId:req.uid,toId:to},{fromId:to,toId:req.uid}]}});if(!f)return res.status(403).json({error:"Only accepted friends can be invited"});let i=await db.roomInvite.create({data:{senderId:req.uid,receiverId:to,roomId:room,expiresAt:new Date(Date.now()+600000)}});send(to,"room:invite",{id:i.id,roomId:room});res.json({ok:true})});
io.use((s,n)=>{try{s.uid=jwt.verify(s.handshake.auth?.token,process.env.JWT_SECRET).sub;n()}catch{n(new Error("Unauthorized"))}});io.on("connection",s=>{let q=users.get(s.uid)||new Set();q.add(s.id);users.set(s.uid,q);
s.on("room:join",async({roomId="lobby"})=>{roomId=String(roomId).slice(0,80);s.join(roomId);let u=await db.user.findUnique({where:{id:s.uid}});let p={id:u.id,username:u.username,position:{x:0,y:0,z:0},rotationY:0,avatar:u.avatar,roomId};players.set(s.id,p);s.emit("room:state",{players:[...players.values()].filter(x=>x.roomId===roomId&&x.id!==p.id)});s.to(roomId).emit("player:joined",p)});
s.on("player:update",d=>{let p=players.get(s.id);if(!p)return;let x=+d?.position?.x,y=+d?.position?.y,z=+d?.position?.z,r=+d?.rotationY;if(![x,y,z,r].every(Number.isFinite)||Math.hypot(x-p.position.x,y-p.position.y,z-p.position.z)>3)return;p.position={x,y,z};p.rotationY=r;s.to(p.roomId).emit("player:update",{id:p.id,position:p.position,rotationY:r})});
s.on("room:chat",async d=>{let p=players.get(s.id),t=String(d?.text||"").trim().slice(0,500);if(!p||p.roomId!==d.roomId||!t)return;let m=await db.message.create({data:{senderId:s.uid,roomId:p.roomId,text:t}});io.to(p.roomId).emit("room:chat",{id:m.id,username:p.username,text:t,createdAt:m.createdAt})});
s.on("room:invite",async d=>{let to=String(d?.receiverId||"");if(to)send(to,"room:invite",{roomId:String(d?.roomId||"lobby")})});
s.on("disconnect",()=>{let p=players.get(s.id);if(p)s.to(p.roomId).emit("player:left",{id:p.id});players.delete(s.id);let q=users.get(s.uid);if(q){q.delete(s.id);if(!q.size)users.delete(s.uid)}})});
srv.listen(Number(process.env.PORT||3001),()=>console.log("My3DWorld server running"));
